name: 'Manual Execução'

on:
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Instalando dependências
        run: npm ci

      - name: Subindo a API
        run: npm start &

      - name: Executando os testes
        run: npx mocha

