name: 'Manual Execução'

on:
  push:
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
      LOGIN_SENHA: ${{ secrets.LOGIN_SENHA }}
    

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Instalando dependências
        run: npm ci

      - name: Verificando secrets
        run: |
          echo "LOGIN_EMAIL length: ${#LOGIN_EMAIL}"
          echo "LOGIN_SENHA length: ${#LOGIN_SENHA}"
          echo "BASE_URL length: ${#BASE_URL}"
          
      - name: Subindo a API
        run: npm start &

      - name: Executando os testes
        run: npx mocha

